apiVersion: v1
kind: Service
metadata:
  name: otus-app-service
spec:
  selector:
    app: otus-app
  ports:
  - protocol: TCP
    port: 80 # порт сервиса
    targetPort: 8000 # порт приложения
  type: ClusterIP
  # type: LoadBalancer
  # type: NodePort
