apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  labels:
    role: myrole
spec:
  containers:
    - name: ubuntu-pod
      image: ubuntu:{{ .Values.containers.ubuntu.version }}
      command:
        - sleep
        - infinity