apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: hello-world.example
      http:
        paths:
          - path: /rec
            pathType: Exact
            backend:
              service:
                name: otus-app-service
                port:
                  number: 80