containers:
  apicontainer:
    name: otus-app
    image: aesedeu/otus_k8s_app:2.0
    container_port: 80
    app_port: 80
    replicas: 2
  ubuntu:
    version: 24.04
  postgres:
    name: postgres-app
    image: postgres:latest
    container_port: 5432
    app_port: 5432
    replicas: 1
    POSTGRES_USER: postgres

autoscale:
  minReplicas: 2
  maxReplicas: 5
  cpuUtilization: 50