containers:
  apicontainer:
    name: otus-app
    image: aesedeu/otus_k8s_app:1.0
    container_port: 8000
    app_port: 80
    replicas: 3
  ubuntu:
    version: 24.04

autoscale:
  minReplicas: 1
  maxReplicas: 5
  cpuUtilization: 50